# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.nebula.installation.v1 import installation_pb2 as salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2
from saltoapis.nebula.installation.v1 import installation_pb2 as salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2


class InstallationServiceStub(object):
    """An installation represents any entity such as a company, office or building
    that contains all the access control objects (access points, access rights,
    users, etc.) that comprise the access control system within a facility.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateInstallation = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/CreateInstallation',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreateInstallationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
                _registered_method=True)
        self.GetInstallation = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/GetInstallation',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetInstallationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
                _registered_method=True)
        self.ListInstallations = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/ListInstallations',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsResponse.FromString,
                _registered_method=True)
        self.UpdateInstallation = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UpdateInstallation',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateInstallationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
                _registered_method=True)
        self.DeleteInstallation = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/DeleteInstallation',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeleteInstallationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
                _registered_method=True)
        self.UndeleteInstallation = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UndeleteInstallation',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UndeleteInstallationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/CreatePolicy',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/GetPolicy',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/ListPolicies',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UpdatePolicy',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/DeletePolicy',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TestPermissions = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/TestPermissions',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsResponse.FromString,
                _registered_method=True)
        self.TransferInstallationOwnership = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/TransferInstallationOwnership',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipResponse.FromString,
                _registered_method=True)
        self.AcceptInstallationOwnership = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/AcceptInstallationOwnership',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipResponse.FromString,
                _registered_method=True)
        self.GetSubscription = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/GetSubscription',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetSubscriptionRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Subscription.FromString,
                _registered_method=True)
        self.UpdateBillingInfo = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UpdateBillingInfo',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateBillingInfoRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.BillingInfo.FromString,
                _registered_method=True)
        self.UpdatePaymentMethod = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UpdatePaymentMethod',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePaymentMethodRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentMethod.FromString,
                _registered_method=True)
        self.UpdateCard = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UpdateCard',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardResponse.FromString,
                _registered_method=True)
        self.CreatePaymentAuthorization = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/CreatePaymentAuthorization',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePaymentAuthorizationRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentAuthorization.FromString,
                _registered_method=True)
        self.ListInvoices = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/ListInvoices',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesResponse.FromString,
                _registered_method=True)
        self.ApplyCoupon = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/ApplyCoupon',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponResponse.FromString,
                _registered_method=True)
        self.UnapplyCoupon = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/UnapplyCoupon',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponResponse.FromString,
                _registered_method=True)
        self.GenerateAuthorizationToken = channel.unary_unary(
                '/salto.nebula.installation.v1.InstallationService/GenerateAuthorizationToken',
                request_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenResponse.FromString,
                _registered_method=True)


class InstallationServiceServicer(object):
    """An installation represents any entity such as a company, office or building
    that contains all the access control objects (access points, access rights,
    users, etc.) that comprise the access control system within a facility.
    """

    def CreateInstallation(self, request, context):
        """Create an installation

        Creates a new installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInstallation(self, request, context):
        """Get an installation

        Retrieves an existing installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInstallations(self, request, context):
        """List installations

        Returns a list of installations that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateInstallation(self, request, context):
        """Update an installation

        Updates an existing installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInstallation(self, request, context):
        """Delete an installation

        Soft deletes an installation. This action can be reversed if required.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeleteInstallation(self, request, context):
        """Undelete an installation

        Undeletes an installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Create a policy

        Creates a policy for the installation. An IAM policy is a collection of
        roles associated to users that define who has what type of access to manage
        access control objects within the installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Get a policy

        Retrieves an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """List policies

        Returns a list of policies that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Update a policy

        Updates an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Delete a policy

        Permanently deletes a policy. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPermissions(self, request, context):
        """Tests permissions

        Returns permissions that a caller has within the installation. If the
        installation does not exist, this will return an empty set of
        permissions, not a NOT_FOUND error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferInstallationOwnership(self, request, context):
        """Transfer installation ownership

        Transfers the ownership of an installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptInstallationOwnership(self, request, context):
        """Accept installation ownership

        Accepts the ownership of an installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubscription(self, request, context):
        """Get a subscription

        Gets an existing subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBillingInfo(self, request, context):
        """Update a subscription's billing information

        Updates an existing subscription's billing information.
        (-- api-linter: core::0134::method-signature=disabled
        aip.dev/not-precedent: We need to do this to simplify the update operation. --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePaymentMethod(self, request, context):
        """Update subscription payment method

        Updates an existing subscription payment method. If there is a payment
        method associated with the subscription, it will be deleted.
        (-- api-linter: core::0134::method-signature=disabled
        aip.dev/not-precedent: We need to do this to simplify the update operation. --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCard(self, request, context):
        """Update subscription payment method's card

        Updates subscription payment method's card. If there is a payment method
        associated with the subscription, it will be deleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePaymentAuthorization(self, request, context):
        """Create a payment authorization

        Creates a payment authorization for the subscription.
        The payment authorization is a process that allows the customer to
        authorize a payment card for future use. This is done by creating a payment
        authorization request. The result of the request is a payment authorization
        that must be authorized by the client in the client's UI.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInvoices(self, request, context):
        """List invoices

        Returns a list of invoices.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyCoupon(self, request, context):
        """Apply a coupon

        Applies a coupon to the subscription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnapplyCoupon(self, request, context):
        """Unapply a coupon

        Unapplies a coupon to the subscription.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAuthorizationToken(self, request, context):
        """Generate authorization token for uninitialized devices

        Generates an authorization token for a client application to use when
        connecting to an uninitialized Salto device. The token contains the
        necessary security material for the client to validate the device's
        identity. This prevents man-in-the-middle (MITM) attacks and ensures the
        client is connecting to a genuine Salto device during its initial
        initialization.

        This token is distinct from other `GenerateAuthorizationToken` methods, it
        is used only for the client to validate the device and does not contain a
        client certificate for authenticating the client itself.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InstallationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInstallation,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreateInstallationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.SerializeToString,
            ),
            'GetInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInstallation,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetInstallationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.SerializeToString,
            ),
            'ListInstallations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInstallations,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsResponse.SerializeToString,
            ),
            'UpdateInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateInstallation,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateInstallationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.SerializeToString,
            ),
            'DeleteInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInstallation,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeleteInstallationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.SerializeToString,
            ),
            'UndeleteInstallation': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeleteInstallation,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UndeleteInstallationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetPolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeletePolicyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TestPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPermissions,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsResponse.SerializeToString,
            ),
            'TransferInstallationOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferInstallationOwnership,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipResponse.SerializeToString,
            ),
            'AcceptInstallationOwnership': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptInstallationOwnership,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipResponse.SerializeToString,
            ),
            'GetSubscription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSubscription,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetSubscriptionRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Subscription.SerializeToString,
            ),
            'UpdateBillingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBillingInfo,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateBillingInfoRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.BillingInfo.SerializeToString,
            ),
            'UpdatePaymentMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePaymentMethod,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePaymentMethodRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentMethod.SerializeToString,
            ),
            'UpdateCard': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCard,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardResponse.SerializeToString,
            ),
            'CreatePaymentAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePaymentAuthorization,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePaymentAuthorizationRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentAuthorization.SerializeToString,
            ),
            'ListInvoices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInvoices,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesResponse.SerializeToString,
            ),
            'ApplyCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyCoupon,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponResponse.SerializeToString,
            ),
            'UnapplyCoupon': grpc.unary_unary_rpc_method_handler(
                    servicer.UnapplyCoupon,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponResponse.SerializeToString,
            ),
            'GenerateAuthorizationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAuthorizationToken,
                    request_deserializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.installation.v1.InstallationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salto.nebula.installation.v1.InstallationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InstallationService(object):
    """An installation represents any entity such as a company, office or building
    that contains all the access control objects (access points, access rights,
    users, etc.) that comprise the access control system within a facility.
    """

    @staticmethod
    def CreateInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/CreateInstallation',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreateInstallationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/GetInstallation',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetInstallationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInstallations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/ListInstallations',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInstallationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UpdateInstallation',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateInstallationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/DeleteInstallation',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeleteInstallationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeleteInstallation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UndeleteInstallation',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UndeleteInstallationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Installation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/CreatePolicy',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePolicyRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/GetPolicy',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetPolicyRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/ListPolicies',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UpdatePolicy',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePolicyRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/DeletePolicy',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.DeletePolicyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/TestPermissions',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TestPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferInstallationOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/TransferInstallationOwnership',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.TransferInstallationOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptInstallationOwnership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/AcceptInstallationOwnership',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.AcceptInstallationOwnershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubscription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/GetSubscription',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GetSubscriptionRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBillingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UpdateBillingInfo',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateBillingInfoRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.BillingInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePaymentMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UpdatePaymentMethod',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdatePaymentMethodRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentMethod.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UpdateCard',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UpdateCardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePaymentAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/CreatePaymentAuthorization',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.CreatePaymentAuthorizationRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.PaymentAuthorization.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInvoices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/ListInvoices',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ListInvoicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/ApplyCoupon',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.ApplyCouponResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnapplyCoupon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/UnapplyCoupon',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.UnapplyCouponResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAuthorizationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.installation.v1.InstallationService/GenerateAuthorizationToken',
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
            salto_dot_nebula_dot_installation_dot_v1_dot_installation__pb2.GenerateAuthorizationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
