# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.longrunning.v1 import operation_pb2 as salto_dot_longrunning_dot_v1_dot_operation__pb2
from saltoapis.longrunning.v1 import operation_pb2 as salto_dot_longrunning_dot_v1_dot_operation__pb2
from saltoapis.nebula.encoder.v1 import encoder_pb2 as salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2
from saltoapis.nebula.encoder.v1 import encoder_pb2 as salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2


class EncoderServiceStub(object):
    """A card encoder is an external device that reads and updates physical card
    keys with access information. This service is responsible for managing
    encoder resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/CreateEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.CreateEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
                _registered_method=True)
        self.GetEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/GetEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GetEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
                _registered_method=True)
        self.ListEncoders = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/ListEncoders',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersResponse.FromString,
                _registered_method=True)
        self.UpdateEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/UpdateEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
                _registered_method=True)
        self.DeleteEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/DeleteEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.DeleteEncoderRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.InitializeEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/InitializeEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.InitializeEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ConfigureEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/ConfigureEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ConfigureEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ResetEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/ResetEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ResetEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.UpdateEncoderFirmware = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/UpdateEncoderFirmware',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderFirmwareRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.BindEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/BindEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderResponse.FromString,
                _registered_method=True)
        self.UnbindEncoder = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/UnbindEncoder',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderResponse.FromString,
                _registered_method=True)
        self.ReadKey = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/ReadKey',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ReadKeyRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.GenerateAuthorizationToken = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/GenerateAuthorizationToken',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenResponse.FromString,
                _registered_method=True)
        self.GenerateFirmwareDownloadUri = channel.unary_unary(
                '/salto.nebula.encoder.v1.EncoderService/GenerateFirmwareDownloadUri',
                request_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateFirmwareDownloadUriRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)


class EncoderServiceServicer(object):
    """A card encoder is an external device that reads and updates physical card
    keys with access information. This service is responsible for managing
    encoder resources.
    """

    def CreateEncoder(self, request, context):
        """Create an encoder

        Creates a new encoder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEncoder(self, request, context):
        """Get an encoder

        Gets an existing encoder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEncoders(self, request, context):
        """List encoders

        Returns a list of encoders that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEncoder(self, request, context):
        """Update an encoder

        Updates an existing encoder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEncoder(self, request, context):
        """Delete an encoder

        Permanently deletes an encoder. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeEncoder(self, request, context):
        """Initialize an encoder

        Initializes an encoder. Encoders need to be initialized before
        you can start to use them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureEncoder(self, request, context):
        """Configure an encoder

        Configures an encoder. Configuring an encoder implies adding some
        information to the encoder based on the current settings.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetEncoder(self, request, context):
        """Reset an encoder

        Resetting a device such as an encoder means returning it to its factory
        settings. Resetting is the process of removing the identity as
        well as all the associated information of an already configured device.
        Once a device has been reset, you need to reconfigure it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEncoderFirmware(self, request, context):
        """Update encoder firmware

        Updates an encoder's firmware. SALTO provides firmware updates
        when new functionality is available or when we fix a bug.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindEncoder(self, request, context):
        """Bind an encoder

        Binds an encoder. Binding an encoder assigns a device
        identifier to the encoder. After binding, the device can then be
        initialized or configured.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindEncoder(self, request, context):
        """Unbind an encoder

        Unbinds an encoder. Unbinding an encoder removes the
        device identifier from the encoder. This may be required in some
        cases where the encoder is not available anymore because, for
        example, it's broken or damaged. Unbinding allows the initialization of
        the replacement device without removing it from the installation. It also
        means the device keeps all the information associated with it, such as
        events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadKey(self, request, context):
        """Read a key

        Reads a key presented on an encoder.
        (-- api-linter: core::0131::synonyms=disabled  --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAuthorizationToken(self, request, context):
        """Generates an authorization token for an encoder

        Generates an authorization token that allows to connect, authenticate and
        authorize against an encoder.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFirmwareDownloadUri(self, request, context):
        """Generate encoder firmware download URI

        Provides the download URI for the latest firmware bundle for the
        encoder. The returned URI can be used to bring the encoder
        firmwares up to latest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EncoderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.CreateEncoderRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.SerializeToString,
            ),
            'GetEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GetEncoderRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.SerializeToString,
            ),
            'ListEncoders': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEncoders,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersResponse.SerializeToString,
            ),
            'UpdateEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.SerializeToString,
            ),
            'DeleteEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.DeleteEncoderRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'InitializeEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.InitializeEncoderRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ConfigureEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ConfigureEncoderRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ResetEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ResetEncoderRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'UpdateEncoderFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEncoderFirmware,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderFirmwareRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'BindEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.BindEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderResponse.SerializeToString,
            ),
            'UnbindEncoder': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindEncoder,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderResponse.SerializeToString,
            ),
            'ReadKey': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadKey,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ReadKeyRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'GenerateAuthorizationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAuthorizationToken,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenResponse.SerializeToString,
            ),
            'GenerateFirmwareDownloadUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFirmwareDownloadUri,
                    request_deserializer=salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateFirmwareDownloadUriRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.encoder.v1.EncoderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salto.nebula.encoder.v1.EncoderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EncoderService(object):
    """A card encoder is an external device that reads and updates physical card
    keys with access information. This service is responsible for managing
    encoder resources.
    """

    @staticmethod
    def CreateEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/CreateEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.CreateEncoderRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/GetEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GetEncoderRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEncoders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/ListEncoders',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ListEncodersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/UpdateEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.Encoder.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/DeleteEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.DeleteEncoderRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/InitializeEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.InitializeEncoderRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/ConfigureEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ConfigureEncoderRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/ResetEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ResetEncoderRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEncoderFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/UpdateEncoderFirmware',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UpdateEncoderFirmwareRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/BindEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.BindEncoderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnbindEncoder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/UnbindEncoder',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.UnbindEncoderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/ReadKey',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.ReadKeyRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAuthorizationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/GenerateAuthorizationToken',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateAuthorizationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFirmwareDownloadUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.encoder.v1.EncoderService/GenerateFirmwareDownloadUri',
            salto_dot_nebula_dot_encoder_dot_v1_dot_encoder__pb2.GenerateFirmwareDownloadUriRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
