load("//:rules.bzl", "load_rules")

package(default_visibility = ['//:__subpackages__'])

load_rules(
    lib_name = 'salto-auth',
    internal_dependencies = [
    ],
    extra_info = {
        'generator': 'python',
    },
)
