# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.nebula.booking.v1 import booking_pb2 as salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2
from saltoapis.nebula.booking.v1 import booking_pb2 as salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2


class BookingServiceStub:
    """The BookingService manages bookings within an installation.

    A booking represents the contractual agreement for a stay, including
    reservation details, dates and guest information. This service handles
    the lifecycle of bookings independently from the physical access control
    systems, allowing reservations to be managed separately from device states
    and access permissions.

    Use this service to create, retrieve, update and delete bookings as part
    of property management operations.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/CreateBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
                _registered_method=True)
        self.GetBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/GetBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
                _registered_method=True)
        self.ListBookings = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/ListBookings',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsResponse.FromString,
                _registered_method=True)
        self.UpdateBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/UpdateBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.UpdateBookingRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
                _registered_method=True)
        self.DeleteBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/DeleteBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CheckInBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/CheckInBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckInBookingRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
                _registered_method=True)
        self.CheckOutBooking = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/CheckOutBooking',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckOutBookingRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
                _registered_method=True)
        self.CreateBookingUser = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/CreateBookingUser',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingUserRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.FromString,
                _registered_method=True)
        self.BatchCreateBookingUsers = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/BatchCreateBookingUsers',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersResponse.FromString,
                _registered_method=True)
        self.GetBookingUser = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/GetBookingUser',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingUserRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.FromString,
                _registered_method=True)
        self.ListBookingUsers = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/ListBookingUsers',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersResponse.FromString,
                _registered_method=True)
        self.DeleteBookingUser = channel.unary_unary(
                '/salto.nebula.booking.v1.BookingService/DeleteBookingUser',
                request_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class BookingServiceServicer:
    """The BookingService manages bookings within an installation.

    A booking represents the contractual agreement for a stay, including
    reservation details, dates and guest information. This service handles
    the lifecycle of bookings independently from the physical access control
    systems, allowing reservations to be managed separately from device states
    and access permissions.

    Use this service to create, retrieve, update and delete bookings as part
    of property management operations.
    """

    def CreateBooking(self, request, context):
        """Create a booking

        Creates a new booking in the specified installation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBooking(self, request, context):
        """Get a booking

        Gets an existing booking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookings(self, request, context):
        """List bookings

        Returns a list of bookings that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBooking(self, request, context):
        """Update a booking

        Updates an existing booking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBooking(self, request, context):
        """Delete a booking

        Permanently deletes a booking. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckInBooking(self, request, context):
        """Check in a booking

        Performs the check-in process for a booking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOutBooking(self, request, context):
        """Check out a booking

        Performs the check-out process for a booking.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateBookingUser(self, request, context):
        """Create a booking user

        Creates a booking's user association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreateBookingUsers(self, request, context):
        """Create a batch of booking users

        Creates a batch of booking users. This method allows the creation of
        multiple booking users in a single operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingUser(self, request, context):
        """Get a booking user

        Retrieves an existing booking's user association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBookingUsers(self, request, context):
        """List booking users

        Lists an existing booking's user associations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBookingUser(self, request, context):
        """Delete a booking user

        Deletes a booking's user association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.SerializeToString,
            ),
            'GetBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.SerializeToString,
            ),
            'ListBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookings,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsResponse.SerializeToString,
            ),
            'UpdateBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.UpdateBookingRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.SerializeToString,
            ),
            'DeleteBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CheckInBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckInBookingRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.SerializeToString,
            ),
            'CheckOutBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOutBooking,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckOutBookingRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.SerializeToString,
            ),
            'CreateBookingUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBookingUser,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingUserRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.SerializeToString,
            ),
            'BatchCreateBookingUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreateBookingUsers,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersResponse.SerializeToString,
            ),
            'GetBookingUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingUser,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingUserRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.SerializeToString,
            ),
            'ListBookingUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBookingUsers,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersResponse.SerializeToString,
            ),
            'DeleteBookingUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBookingUser,
                    request_deserializer=salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.booking.v1.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salto.nebula.booking.v1.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService:
    """The BookingService manages bookings within an installation.

    A booking represents the contractual agreement for a stay, including
    reservation details, dates and guest information. This service handles
    the lifecycle of bookings independently from the physical access control
    systems, allowing reservations to be managed separately from device states
    and access permissions.

    Use this service to create, retrieve, update and delete bookings as part
    of property management operations.
    """

    @staticmethod
    def CreateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/CreateBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/GetBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/ListBookings',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/UpdateBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.UpdateBookingRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/DeleteBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckInBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/CheckInBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckInBookingRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOutBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/CheckOutBooking',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CheckOutBookingRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.Booking.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateBookingUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/CreateBookingUser',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.CreateBookingUserRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCreateBookingUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/BatchCreateBookingUsers',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BatchCreateBookingUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/GetBookingUser',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.GetBookingUserRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.BookingUser.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListBookingUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/ListBookingUsers',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersRequest.SerializeToString,
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.ListBookingUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteBookingUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.booking.v1.BookingService/DeleteBookingUser',
            salto_dot_nebula_dot_booking_dot_v1_dot_booking__pb2.DeleteBookingUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
