# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/type/color.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'salto/type/color.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16salto/type/color.proto\x12\nsalto.type\"O\n\x05\x43olor\x12\x0b\n\x03red\x18\x01 \x01(\x02\x12\r\n\x05green\x18\x02 \x01(\x02\x12\x0c\n\x04\x62lue\x18\x03 \x01(\x02\x12\x12\n\x05\x61lpha\x18\x04 \x01(\x02H\x00\x88\x01\x01\x42\x08\n\x06_alphaB\x9e\x01\n\x12\x63om.saltoapis.typeB\nColorProtoP\x01Z;github.com/saltoapis-internal/saltoapis-go/type/color;color\xaa\x02\x0eSaltoapis.Type\xca\x02\x0eSaltoapis\\Type\xe2\x02\x1aGPBMetadata\\Saltoapis\\Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'salto.type.color_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.saltoapis.typeB\nColorProtoP\001Z;github.com/saltoapis-internal/saltoapis-go/type/color;color\252\002\016Saltoapis.Type\312\002\016Saltoapis\\Type\342\002\032GPBMetadata\\Saltoapis\\Type'
  _globals['_COLOR']._serialized_start=38
  _globals['_COLOR']._serialized_end=117
# @@protoc_insertion_point(module_scope)
