# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/type/time_of_day.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'salto/type/time_of_day.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csalto/type/time_of_day.proto\x12\nsalto.type\"K\n\tTimeOfDay\x12\r\n\x05hours\x18\x01 \x01(\x05\x12\x0f\n\x07minutes\x18\x02 \x01(\x05\x12\x0f\n\x07seconds\x18\x03 \x01(\x05\x12\r\n\x05nanos\x18\x04 \x01(\x05\x42\xaa\x01\n\x12\x63om.saltoapis.typeB\x0eTimeOfDayProtoP\x01ZCgithub.com/saltoapis-internal/saltoapis-go/type/timeofday;timeofday\xaa\x02\x0eSaltoapis.Type\xca\x02\x0eSaltoapis\\Type\xe2\x02\x1aGPBMetadata\\Saltoapis\\Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'salto.type.time_of_day_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\022com.saltoapis.typeB\016TimeOfDayProtoP\001ZCgithub.com/saltoapis-internal/saltoapis-go/type/timeofday;timeofday\252\002\016Saltoapis.Type\312\002\016Saltoapis\\Type\342\002\032GPBMetadata\\Saltoapis\\Type'
  _globals['_TIMEOFDAY']._serialized_start=44
  _globals['_TIMEOFDAY']._serialized_end=119
# @@protoc_insertion_point(module_scope)
