# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.nebula.serviceaccount.v1 import service_account_pb2 as salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2
from saltoapis.nebula.serviceaccount.v1 import service_account_pb2 as salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2


class ServiceAccountServiceStub:
    """A service account is a specialized account used by applications or services to
    authenticate and interact with other applications or services, providing a secure
    and controlled way to manage access to resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateServiceAccount = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/CreateServiceAccount',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
                _registered_method=True)
        self.GetServiceAccount = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/GetServiceAccount',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
                _registered_method=True)
        self.ListServiceAccounts = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/ListServiceAccounts',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsResponse.FromString,
                _registered_method=True)
        self.UpdateServiceAccount = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/UpdateServiceAccount',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.UpdateServiceAccountRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
                _registered_method=True)
        self.DeleteServiceAccount = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/DeleteServiceAccount',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CreateServiceAccountKey = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/CreateServiceAccountKey',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountKeyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.FromString,
                _registered_method=True)
        self.GetServiceAccountKey = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/GetServiceAccountKey',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountKeyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.FromString,
                _registered_method=True)
        self.ListServiceAccountKeys = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/ListServiceAccountKeys',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysResponse.FromString,
                _registered_method=True)
        self.DeleteServiceAccountKey = channel.unary_unary(
                '/salto.nebula.serviceaccount.v1.ServiceAccountService/DeleteServiceAccountKey',
                request_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountKeyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ServiceAccountServiceServicer:
    """A service account is a specialized account used by applications or services to
    authenticate and interact with other applications or services, providing a secure
    and controlled way to manage access to resources.
    """

    def CreateServiceAccount(self, request, context):
        """Create a service account

        Creates a new service account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceAccount(self, request, context):
        """Get a service account

        Retrieves an existing service account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceAccounts(self, request, context):
        """List service accounts

        Returns a list of service accounts that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateServiceAccount(self, request, context):
        """Update the service account

        Updates the existing service account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteServiceAccount(self, request, context):
        """Delete a service account

        Permanently deletes a service account. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateServiceAccountKey(self, request, context):
        """Create a service account key

        Creates a new service account key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServiceAccountKey(self, request, context):
        """Get a service account key

        Retrieves a specific service account key by its resource name.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServiceAccountKeys(self, request, context):
        """List service account keys

        Returns a list of keys for a service account.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteServiceAccountKey(self, request, context):
        """Delete a service account key

        Permanently deletes a service account key.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceAccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServiceAccount,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.SerializeToString,
            ),
            'GetServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceAccount,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.SerializeToString,
            ),
            'ListServiceAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceAccounts,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsResponse.SerializeToString,
            ),
            'UpdateServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateServiceAccount,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.UpdateServiceAccountRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.SerializeToString,
            ),
            'DeleteServiceAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteServiceAccount,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CreateServiceAccountKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateServiceAccountKey,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountKeyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.SerializeToString,
            ),
            'GetServiceAccountKey': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServiceAccountKey,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountKeyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.SerializeToString,
            ),
            'ListServiceAccountKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServiceAccountKeys,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysResponse.SerializeToString,
            ),
            'DeleteServiceAccountKey': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteServiceAccountKey,
                    request_deserializer=salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountKeyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.serviceaccount.v1.ServiceAccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salto.nebula.serviceaccount.v1.ServiceAccountService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServiceAccountService:
    """A service account is a specialized account used by applications or services to
    authenticate and interact with other applications or services, providing a secure
    and controlled way to manage access to resources.
    """

    @staticmethod
    def CreateServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/CreateServiceAccount',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/GetServiceAccount',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/ListServiceAccounts',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/UpdateServiceAccount',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.UpdateServiceAccountRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccount.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteServiceAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/DeleteServiceAccount',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateServiceAccountKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/CreateServiceAccountKey',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.CreateServiceAccountKeyRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServiceAccountKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/GetServiceAccountKey',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.GetServiceAccountKeyRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ServiceAccountKey.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServiceAccountKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/ListServiceAccountKeys',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysRequest.SerializeToString,
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.ListServiceAccountKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteServiceAccountKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.serviceaccount.v1.ServiceAccountService/DeleteServiceAccountKey',
            salto_dot_nebula_dot_serviceaccount_dot_v1_dot_service__account__pb2.DeleteServiceAccountKeyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
