# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.nebula.unit.v1 import unit_pb2 as salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2
from saltoapis.nebula.unit.v1 import unit_pb2 as salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2


class UnitServiceStub(object):
    """UnitService is the service responsible for managing unit resources.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/CreateUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreateUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
                _registered_method=True)
        self.GetUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/GetUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
                _registered_method=True)
        self.ListUnits = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/ListUnits',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsResponse.FromString,
                _registered_method=True)
        self.UpdateUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/UpdateUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdateUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
                _registered_method=True)
        self.DeleteUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/DeleteUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeleteUnitRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.CleanOutUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/CleanOutUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitResponse.FromString,
                _registered_method=True)
        self.MoveInUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/MoveInUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitResponse.FromString,
                _registered_method=True)
        self.MoveOutUnit = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/MoveOutUnit',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitResponse.FromString,
                _registered_method=True)
        self.CreatePolicy = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/CreatePolicy',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreatePolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
                _registered_method=True)
        self.GetPolicy = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/GetPolicy',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetPolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
                _registered_method=True)
        self.ListPolicies = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/ListPolicies',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesResponse.FromString,
                _registered_method=True)
        self.UpdatePolicy = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/UpdatePolicy',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdatePolicyRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
                _registered_method=True)
        self.DeletePolicy = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/DeletePolicy',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeletePolicyRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.TestPermissions = channel.unary_unary(
                '/salto.nebula.unit.v1.UnitService/TestPermissions',
                request_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsResponse.FromString,
                _registered_method=True)


class UnitServiceServicer(object):
    """UnitService is the service responsible for managing unit resources.
    """

    def CreateUnit(self, request, context):
        """Create a unit

        Creates a new unit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnit(self, request, context):
        """Get an existing unit

        Retrieves an existing unit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUnits(self, request, context):
        """List units

        Returns a list of units that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUnit(self, request, context):
        """Update an existing unit

        Updates an existing unit.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUnit(self, request, context):
        """Delete a unit

        Permanently deletes a unit. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanOutUnit(self, request, context):
        """Clean out a unit

        Deprecated: Use [MoveOutUnit][salto.nebula.unit.v1.UnitService.MoveOutUnit]
        (-- api-linter: core::0136::http-uri-suffix=disabled
        aip.dev/not-precedent: We need to do this because clean out is a
        phrasal verb and api-linter don't support using them. --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveInUnit(self, request, context):
        """Move in a unit

        Moves in a unit by creating new occupants and associating them with the unit.
        (-- api-linter: core::0136::http-uri-suffix=disabled
        aip.dev/not-precedent: We need to do this because "move in" is a phrasal
        verb and the api-linter doesn't support using them. --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveOutUnit(self, request, context):
        """Move out a unit

        Moves out a unit by deleting all the occupants belonging to it. This process
        implicitly entails the blocking of the keys that were active within the
        unit. Moving out a unit will not delete the access rights and the
        associated access points that belong to the unit.
        (-- api-linter: core::0136::http-uri-suffix=disabled
        aip.dev/not-precedent: We need to do this because "move out" is a phrasal
        verb and the api-linter doesn't support using them. --)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePolicy(self, request, context):
        """Create a policy

        Creates a new policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPolicy(self, request, context):
        """Get an existing policy

        Retrieves an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPolicies(self, request, context):
        """List policies

        Returns a list of policies that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicy(self, request, context):
        """Update an existing policy

        Updates an existing policy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePolicy(self, request, context):
        """Delete a policy

        Permanently deletes a policy. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestPermissions(self, request, context):
        """Test a permission

        Returns permissions that a caller has on the installation. If the
        installation does not exist, this will return an empty set of
        permissions, not a NOT_FOUND error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreateUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.SerializeToString,
            ),
            'GetUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.SerializeToString,
            ),
            'ListUnits': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUnits,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsResponse.SerializeToString,
            ),
            'UpdateUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdateUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.SerializeToString,
            ),
            'DeleteUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeleteUnitRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'CleanOutUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanOutUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitResponse.SerializeToString,
            ),
            'MoveInUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveInUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitResponse.SerializeToString,
            ),
            'MoveOutUnit': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveOutUnit,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitResponse.SerializeToString,
            ),
            'CreatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePolicy,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreatePolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.SerializeToString,
            ),
            'GetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPolicy,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetPolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.SerializeToString,
            ),
            'ListPolicies': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPolicies,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesResponse.SerializeToString,
            ),
            'UpdatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicy,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdatePolicyRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.SerializeToString,
            ),
            'DeletePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePolicy,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeletePolicyRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'TestPermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.TestPermissions,
                    request_deserializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.unit.v1.UnitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UnitService(object):
    """UnitService is the service responsible for managing unit resources.
    """

    @staticmethod
    def CreateUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/CreateUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreateUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/GetUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUnits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/ListUnits',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListUnitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/UpdateUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdateUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Unit.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/DeleteUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeleteUnitRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanOutUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/CleanOutUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CleanOutUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveInUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/MoveInUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveInUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveOutUnit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/MoveOutUnit',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.MoveOutUnitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/CreatePolicy',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.CreatePolicyRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/GetPolicy',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.GetPolicyRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPolicies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/ListPolicies',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.ListPoliciesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/UpdatePolicy',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.UpdatePolicyRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/DeletePolicy',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.DeletePolicyRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TestPermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.unit.v1.UnitService/TestPermissions',
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsRequest.SerializeToString,
            salto_dot_nebula_dot_unit_dot_v1_dot_unit__pb2.TestPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
