# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.nebula.accesspointgroup.v1 import access_point_group_pb2 as salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2
from saltoapis.nebula.accesspointgroup.v1 import access_point_group_pb2 as salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2


class AccessPointGroupServiceStub(object):
    """Access point group is a collection of access points that can be managed as a
    single entity. It is used to simplify the management of multiple access
    points by grouping them together and applying settings to all of them at
    once. It's also used to optimize the amount of data being used to store all
    access point identifiers by using only an access point group identifier.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAccessPointGroup = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/CreateAccessPointGroup',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
                _registered_method=True)
        self.GetAccessPointGroup = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/GetAccessPointGroup',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
                _registered_method=True)
        self.ListAccessPointGroups = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/ListAccessPointGroups',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsResponse.FromString,
                _registered_method=True)
        self.UpdateAccessPointGroup = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/UpdateAccessPointGroup',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
                _registered_method=True)
        self.DeleteAccessPointGroup = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/DeleteAccessPointGroup',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
                _registered_method=True)
        self.CreateAccessPointGroupAccessPoint = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/CreateAccessPointGroupAccessPoint',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupAccessPointRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
                _registered_method=True)
        self.BatchCreateAccessPointGroupAccessPoints = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/BatchCreateAccessPointGroupAccessPoints',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsResponse.FromString,
                _registered_method=True)
        self.GetAccessPointGroupAccessPoint = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/GetAccessPointGroupAccessPoint',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupAccessPointRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
                _registered_method=True)
        self.ListAccessPointGroupAccessPoints = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/ListAccessPointGroupAccessPoints',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsResponse.FromString,
                _registered_method=True)
        self.UpdateAccessPointGroupAccessPoint = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/UpdateAccessPointGroupAccessPoint',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupAccessPointRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
                _registered_method=True)
        self.DeleteAccessPointGroupAccessPoint = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/DeleteAccessPointGroupAccessPoint',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupAccessPointRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BatchDeleteAccessPointGroupAccessPoints = channel.unary_unary(
                '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/BatchDeleteAccessPointGroupAccessPoints',
                request_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsResponse.FromString,
                _registered_method=True)


class AccessPointGroupServiceServicer(object):
    """Access point group is a collection of access points that can be managed as a
    single entity. It is used to simplify the management of multiple access
    points by grouping them together and applying settings to all of them at
    once. It's also used to optimize the amount of data being used to store all
    access point identifiers by using only an access point group identifier.
    """

    def CreateAccessPointGroup(self, request, context):
        """Create an access point group

        Creates an access point group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessPointGroup(self, request, context):
        """Get an access point group

        Gets an existing access point group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessPointGroups(self, request, context):
        """List access point groups

        Returns a list of access point groups that have been previously
        created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccessPointGroup(self, request, context):
        """Update an access point group

        Updates an existing access point group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccessPointGroup(self, request, context):
        """Delete an access point group

        Soft deletes an access point group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAccessPointGroupAccessPoint(self, request, context):
        """Create an access point

        Creates an access point group's access point association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchCreateAccessPointGroupAccessPoints(self, request, context):
        """Create a batch of access point group access points

        Creates a batch of access point group's access points association.
        This method allows the creation of multiple access point group's access points in a single operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccessPointGroupAccessPoint(self, request, context):
        """Get an access point

        Retrieves an existing access point group's access point association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAccessPointGroupAccessPoints(self, request, context):
        """List access points

        Lists an existing access point group's access point associations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccessPointGroupAccessPoint(self, request, context):
        """Update an access point

        Updates an existing access point group's access point association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAccessPointGroupAccessPoint(self, request, context):
        """Delete an access point

        Deletes an access point group's access point association.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDeleteAccessPointGroupAccessPoints(self, request, context):
        """Delete a batch of access point group access point associations

        Deletes a batch of access point group access point associations. This method allows the
        deletion of multiple access point group access points in a single operation. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessPointGroupServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAccessPointGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccessPointGroup,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.SerializeToString,
            ),
            'GetAccessPointGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessPointGroup,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.SerializeToString,
            ),
            'ListAccessPointGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessPointGroups,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsResponse.SerializeToString,
            ),
            'UpdateAccessPointGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccessPointGroup,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.SerializeToString,
            ),
            'DeleteAccessPointGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccessPointGroup,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.SerializeToString,
            ),
            'CreateAccessPointGroupAccessPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAccessPointGroupAccessPoint,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupAccessPointRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.SerializeToString,
            ),
            'BatchCreateAccessPointGroupAccessPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchCreateAccessPointGroupAccessPoints,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsResponse.SerializeToString,
            ),
            'GetAccessPointGroupAccessPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccessPointGroupAccessPoint,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupAccessPointRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.SerializeToString,
            ),
            'ListAccessPointGroupAccessPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessPointGroupAccessPoints,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsResponse.SerializeToString,
            ),
            'UpdateAccessPointGroupAccessPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccessPointGroupAccessPoint,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupAccessPointRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.SerializeToString,
            ),
            'DeleteAccessPointGroupAccessPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAccessPointGroupAccessPoint,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupAccessPointRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BatchDeleteAccessPointGroupAccessPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDeleteAccessPointGroupAccessPoints,
                    request_deserializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.accesspointgroup.v1.AccessPointGroupService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salto.nebula.accesspointgroup.v1.AccessPointGroupService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AccessPointGroupService(object):
    """Access point group is a collection of access points that can be managed as a
    single entity. It is used to simplify the management of multiple access
    points by grouping them together and applying settings to all of them at
    once. It's also used to optimize the amount of data being used to store all
    access point identifiers by using only an access point group identifier.
    """

    @staticmethod
    def CreateAccessPointGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/CreateAccessPointGroup',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessPointGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/GetAccessPointGroup',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessPointGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/ListAccessPointGroups',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccessPointGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/UpdateAccessPointGroup',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccessPointGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/DeleteAccessPointGroup',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroup.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAccessPointGroupAccessPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/CreateAccessPointGroupAccessPoint',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.CreateAccessPointGroupAccessPointRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchCreateAccessPointGroupAccessPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/BatchCreateAccessPointGroupAccessPoints',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchCreateAccessPointGroupAccessPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccessPointGroupAccessPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/GetAccessPointGroupAccessPoint',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.GetAccessPointGroupAccessPointRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAccessPointGroupAccessPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/ListAccessPointGroupAccessPoints',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.ListAccessPointGroupAccessPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAccessPointGroupAccessPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/UpdateAccessPointGroupAccessPoint',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.UpdateAccessPointGroupAccessPointRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.AccessPointGroupAccessPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAccessPointGroupAccessPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/DeleteAccessPointGroupAccessPoint',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.DeleteAccessPointGroupAccessPointRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDeleteAccessPointGroupAccessPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.accesspointgroup.v1.AccessPointGroupService/BatchDeleteAccessPointGroupAccessPoints',
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsRequest.SerializeToString,
            salto_dot_nebula_dot_accesspointgroup_dot_v1_dot_access__point__group__pb2.BatchDeleteAccessPointGroupAccessPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
