# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: salto/nebula/type/technology.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'salto/nebula/type/technology.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"salto/nebula/type/technology.proto\x12\x11salto.nebula.type*\\\n\x10\x41ppKeyTechnology\x12\"\n\x1e\x41PP_KEY_TECHNOLOGY_UNSPECIFIED\x10\x00\x12\x07\n\x03\x42LE\x10\x01\x12\x0b\n\x07NFC_HCE\x10\x02\x12\x0e\n\nNFC_READER\x10\x03\x42\xd0\x01\n\x19\x63om.saltoapis.nebula.typeB\x0fTechnologyProtoP\x01ZLgithub.com/saltoapis-internal/saltoapis-go/nebula/type/technology;technology\xaa\x02\x15Saltoapis.Nebula.Type\xca\x02\x15Saltoapis\\Nebula\\Type\xe2\x02!GPBMetadata\\Saltoapis\\Nebula\\Typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'salto.nebula.type.technology_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.saltoapis.nebula.typeB\017TechnologyProtoP\001ZLgithub.com/saltoapis-internal/saltoapis-go/nebula/type/technology;technology\252\002\025Saltoapis.Nebula.Type\312\002\025Saltoapis\\Nebula\\Type\342\002!GPBMetadata\\Saltoapis\\Nebula\\Type'
  _globals['_APPKEYTECHNOLOGY']._serialized_start=57
  _globals['_APPKEYTECHNOLOGY']._serialized_end=149
# @@protoc_insertion_point(module_scope)
