# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from saltoapis.longrunning.v1 import operation_pb2 as salto_dot_longrunning_dot_v1_dot_operation__pb2
from saltoapis.longrunning.v1 import operation_pb2 as salto_dot_longrunning_dot_v1_dot_operation__pb2
from saltoapis.nebula.intercomadaptor.v1 import intercom_adaptor_pb2 as salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2
from saltoapis.nebula.intercomadaptor.v1 import intercom_adaptor_pb2 as salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2


class IntercomAdaptorServiceStub(object):
    """An intercom adaptor is a device that can be connected to an existing intercom
    system close to the telephone handset, without affecting its proper
    functioning. Its main function is to convert the intercom system to become
    part of the access control system.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/CreateIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.CreateIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
                _registered_method=True)
        self.GetIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GetIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GetIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
                _registered_method=True)
        self.ListIntercomAdaptors = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ListIntercomAdaptors',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsResponse.FromString,
                _registered_method=True)
        self.UpdateIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UpdateIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
                _registered_method=True)
        self.DeleteIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/DeleteIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.DeleteIntercomAdaptorRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.BindIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/BindIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorResponse.FromString,
                _registered_method=True)
        self.UnbindIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UnbindIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorResponse.FromString,
                _registered_method=True)
        self.InitializeIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/InitializeIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.InitializeIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ConfigureIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ConfigureIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ConfigureIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.ResetIntercomAdaptor = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ResetIntercomAdaptor',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ResetIntercomAdaptorRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.UpdateIntercomAdaptorFirmware = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UpdateIntercomAdaptorFirmware',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorFirmwareRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)
        self.GenerateAuthorizationToken = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GenerateAuthorizationToken',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
                response_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenResponse.FromString,
                _registered_method=True)
        self.GenerateFirmwareDownloadUri = channel.unary_unary(
                '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GenerateFirmwareDownloadUri',
                request_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateFirmwareDownloadUriRequest.SerializeToString,
                response_deserializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
                _registered_method=True)


class IntercomAdaptorServiceServicer(object):
    """An intercom adaptor is a device that can be connected to an existing intercom
    system close to the telephone handset, without affecting its proper
    functioning. Its main function is to convert the intercom system to become
    part of the access control system.
    """

    def CreateIntercomAdaptor(self, request, context):
        """Create an intercom adaptor

        Creates a new intercom adaptor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIntercomAdaptor(self, request, context):
        """Get an intercom adaptor

        Gets an existing intercom adaptor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListIntercomAdaptors(self, request, context):
        """List intercom adaptors

        Returns a list of intercom adaptors that have been previously created.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIntercomAdaptor(self, request, context):
        """Update an intercom adaptor

        Updates an existing intercom adaptor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteIntercomAdaptor(self, request, context):
        """Delete an intercom adaptor

        Permanently deletes an intercom adaptor. This cannot be undone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BindIntercomAdaptor(self, request, context):
        """Bind an intercom adaptor

        Binds an intercom adaptor. Binding an intercom adaptor assigns a device
        identifier to the intercom adaptor. After binding, the device can then be
        initialized or configured.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnbindIntercomAdaptor(self, request, context):
        """Unbind an intercom adaptor

        Unbinds an intercom adaptor. Unbinding an intercom adaptor removes the
        device identifier from the intercom adaptor. This may be required in some
        cases where the intercom adaptor is not available anymore because, for
        example, it's broken or damaged. Unbinding allows the initialization of
        the replacement device without removing it from the installation. It also
        means the device keeps all the information associated with it, such as
        events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitializeIntercomAdaptor(self, request, context):
        """Initialize an intercom adaptor

        Initializes an intercom adaptor. Intercom adaptors need to be initialized
        before you can start to use them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureIntercomAdaptor(self, request, context):
        """Configure an intercom adaptor

        Configures an intercom adaptor. Configuring an intercom adaptor implies
        adding some information to the intercom adaptor such as setting the time
        zone.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetIntercomAdaptor(self, request, context):
        """Reset an intercom adaptor

        Resetting a device such as an intercom adaptor means returning it to its
        factory settings. Resetting is the process of removing the identity as
        well as all the associated information of an already configured device.
        Once a device has been reset, you need to reconfigure it.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateIntercomAdaptorFirmware(self, request, context):
        """Update intercom adaptor firmware

        Updates an intercom adaptor's firmware. SALTO provides firmware updates
        when new functionality is available or when we fix a bug.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateAuthorizationToken(self, request, context):
        """Generates an authorization token for an intercom adaptor

        Generates an authorization token that allows to connect, authenticate and
        authorize against an intercom adaptor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFirmwareDownloadUri(self, request, context):
        """Generate intercom adaptor firmware download URI

        Provides the download URI for the latest firmware bundle for the
        intercom adaptor. The returned URI can be used to bring the intercom
        adaptor firmwares up to latest.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntercomAdaptorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.CreateIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.SerializeToString,
            ),
            'GetIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GetIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.SerializeToString,
            ),
            'ListIntercomAdaptors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListIntercomAdaptors,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsResponse.SerializeToString,
            ),
            'UpdateIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.SerializeToString,
            ),
            'DeleteIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.DeleteIntercomAdaptorRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'BindIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.BindIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorResponse.SerializeToString,
            ),
            'UnbindIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.UnbindIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorResponse.SerializeToString,
            ),
            'InitializeIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.InitializeIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ConfigureIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ConfigureIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'ResetIntercomAdaptor': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetIntercomAdaptor,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ResetIntercomAdaptorRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'UpdateIntercomAdaptorFirmware': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateIntercomAdaptorFirmware,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorFirmwareRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
            'GenerateAuthorizationToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAuthorizationToken,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenRequest.FromString,
                    response_serializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenResponse.SerializeToString,
            ),
            'GenerateFirmwareDownloadUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateFirmwareDownloadUri,
                    request_deserializer=salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateFirmwareDownloadUriRequest.FromString,
                    response_serializer=salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salto.nebula.intercomadaptor.v1.IntercomAdaptorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IntercomAdaptorService(object):
    """An intercom adaptor is a device that can be connected to an existing intercom
    system close to the telephone handset, without affecting its proper
    functioning. Its main function is to convert the intercom system to become
    part of the access control system.
    """

    @staticmethod
    def CreateIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/CreateIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.CreateIntercomAdaptorRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GetIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GetIntercomAdaptorRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListIntercomAdaptors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ListIntercomAdaptors',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ListIntercomAdaptorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UpdateIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.IntercomAdaptor.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/DeleteIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.DeleteIntercomAdaptorRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BindIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/BindIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.BindIntercomAdaptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnbindIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UnbindIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UnbindIntercomAdaptorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitializeIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/InitializeIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.InitializeIntercomAdaptorRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ConfigureIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ConfigureIntercomAdaptorRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetIntercomAdaptor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/ResetIntercomAdaptor',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.ResetIntercomAdaptorRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateIntercomAdaptorFirmware(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/UpdateIntercomAdaptorFirmware',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.UpdateIntercomAdaptorFirmwareRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateAuthorizationToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GenerateAuthorizationToken',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenRequest.SerializeToString,
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateAuthorizationTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFirmwareDownloadUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/salto.nebula.intercomadaptor.v1.IntercomAdaptorService/GenerateFirmwareDownloadUri',
            salto_dot_nebula_dot_intercomadaptor_dot_v1_dot_intercom__adaptor__pb2.GenerateFirmwareDownloadUriRequest.SerializeToString,
            salto_dot_longrunning_dot_v1_dot_operation__pb2.Operation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
